"""participant_is_self

Revision ID: 68da79b49297
Revises: e4a51a0e225f
Create Date: 2024-10-10 22:31:34.971641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68da79b49297"
down_revision: Union[str, None] = "e4a51a0e225f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participants", sa.Column("is_self", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participants", "is_self")
    # ### end Alembic commands ###
